# Generated by Django 4.2.6 on 2023-12-11 23:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('filebase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='file',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 1, 13, 8, 937645)),
        ),
        migrations.AddField(
            model_name='file',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
