# Generated by Django 4.2.6 on 2023-12-15 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filebase', '0003_file_description_alter_file_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='File', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 4, 54, 43, 626636)),
        ),
    ]
